/*
    def remote = [:]
    remote.name = 'sil-toolserver-1'
    remote.host = '10.134.134.10'
    remote.user = 'cust'
    remote.password = 'AvayaSIL123$'
    remote.allowAnyHosts = true
*/

pipeline {
    agent any
    stages {
        stage('Copy file to Linux Build Server') {
            steps {
                echo "STAGE: Copy file to Linux Build Server"
                echo "${Lab}"
                echo "Task: ${Task}"
                echo "TenantIndex: ${TenantIndex}"
                echo "Features: ${Features}"
                script{
                    task = "${Task}"
                    lab = "${Lab}"
                    command = "python3 app.py --lab ${lab} --task ${task}"
                    features = "${Features}".split(',').collect{it as String}
                    println("Features: " + features)
                    for(i = 0; i < features.size(); i++){
                        features[i].replaceAll("\\s","")
                        if (features[i] == ""){
                            features.remove(i);
                            i--;
                        }
                    }
                    if (features.size() != 0) {
                        command += " --features "
                        for (i = 0; i < features.size(); i +=2){
                            command = command + features[i] + " "
                        } 
                    }  
                }
                echo "Command: ${Command}"
            }
        }
        stage('Placing files') {
            steps {
                echo 'STAGE: Placing files'
            }
        }
        stage('Configuration') {
            steps {
                echo "STAGE: CONFIGURATION"
            }
        }
        stage('Login Agent') {
            steps {
                echo "STAGE: LOGIN AGENT"
            }
        }

        stage('Inject Traffic Test') {
            steps {
                echo "STAGE: Inject Traffic Test"
            }
        }

        stage('Other stages') {
            steps {
                echo "STAGE: ...."
            }
        }        
    }
}

        