/*
    def remote = [:]
    remote.name = 'sil-toolserver-1'
    remote.host = '10.134.134.10'
    remote.user = 'cust'
    remote.password = 'AvayaSIL123$'
    remote.allowAnyHosts = true
*/
pipeline {
    agent any
    stages {
        stage('Branch') {
            steps{
                echo "STAGE: BRANCH"
                echo "This Pipeline is on branch dev"
            }
        }
        stage('Configuration') {
            steps{
                echo "STAGE: CONFIGURATION"
                echo "Run Script on branch: ${Branch}"
                echo "Param:"
                echo "  - Lab: ${Lab}" 
                echo "  - Task: ${Task}"
                echo "  - Tenant Index: ${params['Tenant Index']}"
                echo "  - Tenant Features: ${params['Tenant Features']}"
                echo "  - Chat Traffic: ${params['Chat Traffic']}"
                echo "  - Voice Traffic: ${params['Voice Traffic']}"
                echo "  - Email Traffic: ${params['Email Traffic']}"
                echo "  - Messaging Traffic: ${params['Messaging Traffic']}"
                echo "Command: python3 app.py --lab ${Lab} --task ${Task} --tenant ${params['Tenant Index']} --features ${params['Tenant Features']}"
            }
        }  
    }
}

        